
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 03 22:10:39 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 19;
  public static final int LBRACKET = 48;
  public static final int CHAR = 54;
  public static final int CONST = 7;
  public static final int GE = 33;
  public static final int LPAREN = 46;
  public static final int SEMI = 41;
  public static final int CONTINUE = 15;
  public static final int FOR = 16;
  public static final int MINUS = 27;
  public static final int RPAREN = 47;
  public static final int AND = 37;
  public static final int LT = 36;
  public static final int RANGE = 23;
  public static final int OR = 38;
  public static final int IN = 22;
  public static final int BOOL = 53;
  public static final int COMMA = 43;
  public static final int CLASS = 4;
  public static final int INC = 24;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int ASSIGN = 39;
  public static final int IF = 8;
  public static final int DOT = 44;
  public static final int LE = 35;
  public static final int FINDANY = 18;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 49;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 52;
  public static final int MOD = 30;
  public static final int NEQ = 32;
  public static final int IDENT = 55;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int EQ = 31;
  public static final int ARROW = 40;
  public static final int COLON = 42;
  public static final int LBRACE = 50;
  public static final int ELSE = 6;
  public static final int READ = 11;
  public static final int WHILE = 21;
  public static final int RBRACE = 51;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int QUESTION = 45;
  public static final int DEC = 25;
  public static final int GT = 34;
  public static final int PRINT = 10;
  public static final int LENGTH = 17;
  public static final int DO = 20;
}

